---
- hosts: localhost
  tasks:
    - name: Update APT package manager repositories cache
      ignore_errors: True
      become: true
      apt:
        update_cache: yes
    - name: Install NodeJs and npm
      ignore_errors: True
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - nodejs
           - npm

