---
- hosts: localhost
  tasks:
    - name: add Microsoft package signing key
      ignore_errors: True
      shell: | 
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
      args:
        warn: no
    - name: Update APT package manager repositories cache
      ignore_errors: True
      become: true
      apt:
        update_cache: yes
    - name: Install .NET using Ansible
      ignore_errors: True
      become: yes
      apt:
        name: dotnet-sdk-5.0
